name: mobize_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  internet_connection_checker: ^1.0.0+1

  # Notifcation Service
  onesignal_flutter: ^5.0.2

  # Firebase library
  firebase_core: ^2.11.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.10.0
  google_sign_in: ^6.1.5

  # State Management
  flutter_bloc: ^8.1.2

  # Clean Code Library
  equatable: ^2.0.5
  dartz: ^0.10.1
  get_it: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - fonts/
  fonts:
    - family: Bahij_TheSansArabic
      fonts:
        - asset: fonts/Bahij_TheSansArabic-Plain.ttf
          weight: 400
